export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET';

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST';
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS';
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';
