export const USER_LOGIN_REQUEST  = 'USER_LOGIN_REQUEST'; 
export const USER_LOGIN_SUCCESS  = 'USER_LOGIN_SUCCESS'; 
export const USER_LOGIN_FAIL  = 'USER_LOGIN_FAIL'; 

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const USER_REGISTER_REQUEST  = 'USER_REGISTER_REQUEST'; 
export const USER_REGISTER_SUCCESS  = 'USER_REGISTER_SUCCESS'; 
export const USER_REGISTER_FAIL  = 'USER_REGISTER_FAIL'; 

export const USER_LOAD_REQUEST  = 'USER_LOAD_REQUEST'; 
export const USER_LOAD_SUCCESS  = 'USER_LOAD_SUCCESS'; 
export const USER_LOAD_FAIL  = 'USER_LOAD_FAIL'; 

export const USER_AVATAR_REQUEST  = 'USER_AVATAR_REQUEST'; 
export const USER_AVATAR_SUCCESS  = 'USER_AVATAR_SUCCESS'; 
export const USER_AVATAR_FAIL  = 'USER_AVATAR_FAIL';

export const USER_LOGOUT_REQUEST  = 'USER_LOGOUT_REQUEST'; 
export const USER_LOGOUT_SUCCESS  = 'USER_LOGOUT_SUCCESS'; 
export const USER_LOGOUT_FAIL  = 'USER_LOGOUT_FAIL';

export const USER_UPDATE_REQUEST  = 'USER_UPDATE_REQUEST'; 
export const USER_UPDATE_SUCCESS  = 'USER_UPDATE_SUCCESS'; 
export const USER_UPDATE_FAIL  = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const UPDATE_PASSWORD_REQUEST  = 'UPDATE_PASSWORD_REQUEST'; 
export const UPDATE_PASSWORD_SUCCESS  = 'UPDATE_PASSWORD_SUCCESS'; 
export const UPDATE_PASSWORD_FAIL  = 'UPDATE_PASSWORD_FAIL';
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'

export const FORGOT_PASSWORD_REQUEST  = 'FORGOT_PASSWORD_REQUEST'; 
export const FORGOT_PASSWORD_SUCCESS  = 'FORGOT_PASSWORD_SUCCESS'; 
export const FORGOT_PASSWORD_FAIL  = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET';

export const RESET_PASSWORD_REQUEST  = 'RESET_PASSWORD_REQUEST'; 
export const RESET_PASSWORD_SUCCESS  = 'RESET_PASSWORD_SUCCESS'; 
export const RESET_PASSWORD_FAIL  = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET';

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_RESET = 'DELETE_USER_RESET';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
